#include "rbtree.h"

int main() {
    struct Rbnode* root = 0;
    struct Rbnode node0 = {6,0,0,0,0};
    struct Rbnode node1 = {1,0,0,0,0};
    struct Rbnode node2 = {4,0,0,0,0};
    struct Rbnode node3 = {8,0,0,0,0};
    struct Rbnode node4 = {3,0,0,0,0};
    struct Rbnode node5 = {2,0,0,0,0};
    struct Rbnode node6 = {5,0,0,0,0};
    struct Rbnode node7 = {7,0,0,0,0};
    struct Rbnode node8 = {0,0,0,0,0};
    struct Rbnode node9 = {9,0,0,0,0};
    struct Rbnode node10 = {12,0,0,0,0};
    struct Rbnode node11 = {10,0,0,0,0};
    struct Rbnode node12 = {11,0,0,0,0};
    printf("---------------------insert 6\n");
    rb_insert(&root, &node1);
    rbprint_root(root);
    printf("---------------------insert 1\n");
    rb_insert(&root, &node2);
    rbprint_root(root);
    printf("---------------------insert 4\n");
    rb_insert(&root, &node3);
    rbprint_root(root);
    printf("---------------------insert 8\n");
    rb_insert(&root, &node4);
    rbprint_root(root);
    printf("---------------------insert 3\n");
    rb_insert(&root, &node5);
    rbprint_root(root);
    printf("---------------------insert 2\n");
    rb_insert(&root, &node0);
    rbprint_root(root);
    printf("---------------------insert 5\n");
    rb_insert(&root, &node6);
    rbprint_root(root);
    printf("---------------------insert 7\n");
    rb_insert(&root, &node7);
    rbprint_root(root);
    printf("---------------------insert 0\n");
    rb_insert(&root, &node8);
    rbprint_root(root);
    printf("---------------------insert 9\n");
    rb_insert(&root, &node9);
    rbprint_root(root);
    printf("---------------------insert 12\n");
    rb_insert(&root, &node10);
    rbprint_root(root);
    printf("---------------------insert 10\n");
    rb_insert(&root, &node11);
    rbprint_root(root);
    printf("---------------------insert 11\n");
    rb_insert(&root, &node12);
    rbprint_root(root);

    printf("---------------------delete 12\n");
    rb_delete(&root, &node10);
    rbprint_root(root);
    printf("---------------------delete 11\n");
    rb_delete(&root, &node12);
    rbprint_root(root);
    printf("---------------------delete 4\n");
    rb_delete(&root, &node2);
    rbprint_root(root);
    printf("---------------------delete 2\n");
    rb_delete(&root, &node5);
    rbprint_root(root);
    printf("---------------------delete 1\n");
    rb_delete(&root, &node1);
    rbprint_root(root);
    printf("---------------------delete 3\n");
    rb_delete(&root, &node4);
    rbprint_root(root);
    printf("---------------------delete 8\n");
    rb_delete(&root, &node3);
    rbprint_root(root);
    printf("---------------------delete 0\n");
    rb_delete(&root, &node8);
    rbprint_root(root);
    printf("---------------------delete 5\n");
    rb_delete(&root, &node6);
    rbprint_root(root);
    printf("---------------------delete 7\n");
    rb_delete(&root, &node7);
    rbprint_root(root);
    printf("---------------------delete 10\n");
    rb_delete(&root, &node11);
    rbprint_root(root);
    printf("---------------------delete 9\n");
    rb_delete(&root, &node9);
    rbprint_root(root);
    printf("---------------------delete 6\n");
    rb_delete(&root, &node0);
    rbprint_root(root);
}
